version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_management_db
    networks:
      - my_network

  php_apache:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql_db
    networks:
      - my_network

networks:
  my_network:
